name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - "stacks/**"
      - "modules/**"

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: terraform-apply
  cancel-in-progress: false

jobs:
  terraform:
    uses: Bedatty-Engineering/modules-hub/.github/workflows/terraform/apply.yml@main
    with:
      terraform_version: "1.7.5"
    secrets: inherit