name: Terraform Plan

on:
  pull_request:
    branches:
      - main
    paths:
      - "stacks/**"
      - "modules/**"

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: terraform-plan-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  terraform:
    uses: Bedatty-Engineering/modules-hub/.github/workflows/terraform/plan.yml@main
    with:
      terraform_version: "1.7.5"
      concurrency_group: ${{ github.event.pull_request.number }}
    secrets: inherit
